### ISSUE TITLE
Deadlock if the connection is still being used while HttpClient is closing

### ISSUE THREAD

**Issue by testn** [eclipse/vert.x#1247]
This happens in Vert.x 3.2. In thread 5717, we hold the lock on HttpClientImpl.close (lock #1) and then we try to acquire a lock on ClientConnection.close (lock #2). In thread 7035, we hold a lock #2 in ClientConnection.handleClosed and try to hold a lock #1 at HttpClientImpl.checkClosed. And boom, we get a deadlock. 

I don't have a good repro now since it's quite hard to reproduce consistently. But I can demonstrate from the stack trace:

```
Thread 5717: (state = BLOCKED)
 - io.vertx.core.http.impl.ClientConnection.close() @bci=0, line=352 (Interpreted frame)
 - io.vertx.core.http.impl.HttpClientImpl.close() @bci=46, line=642 (Interpreted frame)

Thread 7035: (state = BLOCKED)
 - io.vertx.core.http.impl.HttpClientImpl.checkClosed() @bci=0, line=791 (Interpreted frame)
 - io.vertx.core.http.impl.HttpClientImpl.doRequest(io.vertx.core.http.HttpMethod, java.lang.String, int, java.lang.String, io.vertx.core.MultiMap) @bci=23, line=782 (Interpreted frame)
 - io.vertx.core.http.impl.HttpClientImpl.request(io.vertx.core.http.HttpMethod, int, java.lang.String, java.lang.String) @bci=7, line=338 (Interpreted frame)
 - io.vertx.core.http.impl.HttpClientImpl.get(int, java.lang.String, java.lang.String) @bci=7, line=348 (Interpreted frame)
          . 
          .
          .
 - io.vertx.core.http.impl.HttpClientRequestImpl.lambda$exceptionHandler$78(io.vertx.core.Handler, java.lang.Throwable) @bci=6, line=262 (Interpreted frame)
 - io.vertx.core.http.impl.HttpClientRequestImpl$$Lambda$21.handle(java.lang.Object) @bci=12 (Interpreted frame)
 - io.vertx.core.http.impl.HttpClientRequestImpl.handleException(java.lang.Throwable) @bci=21, line=384 (Interpreted frame)
 - io.vertx.core.http.impl.ClientConnection.handleClosed() @bci=59, line=307 (Interpreted frame)
 - io.vertx.core.net.impl.VertxHandler$$Lambda$43.run() @bci=4 (Interpreted frame)
 - io.vertx.core.impl.ContextImpl.lambda$wrapTask$16(boolean, io.vertx.core.impl.ContextTask, io.vertx.core.Handler) @bci=167, line=333 (Compiled frame)
 - io.vertx.core.impl.ContextImpl$$Lambda$15.run() @bci=16 (Compiled frame)
 - io.vertx.core.impl.ContextImpl.executeFromIO(io.vertx.core.impl.ContextTask) @bci=17, line=225 (Compiled frame)
 - io.vertx.core.net.impl.VertxHandler.channelInactive(io.netty.channel.ChannelHandlerContext) @bci=37, line=99 (Interpreted frame)
 - io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive() @bci=8, line=218 (Interpreted frame)
 - io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive() @bci=20, line=204 (Interpreted frame)
 - io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(io.netty.channel.ChannelHandlerContext) @bci=1, line=75 (Interpreted frame)
 - io.netty.handler.timeout.IdleStateHandler.channelInactive(io.netty.channel.ChannelHandlerContext) @bci=6, line=257 (Interpreted frame)
 - io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive() @bci=8, line=218 (Interpreted frame)
 - io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive() @bci=20, line=204 (Interpreted frame)
 - io.netty.handler.codec.ByteToMessageDecoder.channelInactive(io.netty.channel.ChannelHandlerContext) @bci=86, line=332 (Interpreted frame)
 - io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(io.netty.channel.ChannelHandlerContext) @bci=2, line=212 (Interpreted frame)
 - io.netty.channel.CombinedChannelDuplexHandler.channelInactive(io.netty.channel.ChannelHandlerContext) @bci=5, line=132 (Interpreted frame)
 - io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive() @bci=8, line=218 (Interpreted frame)
 - io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive() @bci=20, line=204 (Interpreted frame)
 - io.netty.channel.DefaultChannelPipeline.fireChannelInactive() @bci=4, line=828 (Interpreted frame)
 - io.netty.channel.AbstractChannel$AbstractUnsafe$7.run() @bci=10, line=625 (Interpreted frame)
 - io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(long) @bci=26, line=358 (Compiled frame)
 - io.netty.channel.nio.NioEventLoop.run() @bci=106, line=357 (Compiled frame)
 - io.netty.util.concurrent.SingleThreadEventExecutor$2.run() @bci=13, line=112 (Compiled frame)
 - java.lang.Thread.run() @bci=11, line=745 (Compiled frame)
```

**Comment by vietj** [comment]
do you have a longer trace for thread 5717 ?

**Comment by vietj** [comment]
can you post the full stack trace of 7035 ?

**Comment by vietj** [comment]
it seems that it could be removed by copying the connection to close in HttpClientImp close and close them outside of the synchronized block.

**Comment by vietj** [comment]
in 7035: 

io.vertx.core.http.impl.HttpClientRequestImpl.lambda$exceptionHandler$78(io.vertx.core.Handler, java.lang.Throwable) @bci=6, line=262 (Interpreted frame)

this seem to be your code doing something in the exception handler that creates the deadlock, that does a get. 

I think it can be reproduced and then fixed by calling the exceptionHandler outside of the synchronized block. As workaround you could do a vertx.runOnContext() to wrap the get. It should remove this deadlock, can you give a try and tell us how it goes ?

**Comment by testn** [comment]
That's pretty much all the stack trace. For 5717, I just close the `HttpClient` from main thread.

**Comment by testn** [comment]
If HttpClient can not be closed safely from non vertx thread that owns `HttpClient`, it should probably be changed to close asynchronously and with a callback instead.

**Comment by testn** [comment]
What do you plan to do with this one?

**Comment by vietj** [comment]
throw an exception with an explanatory message when context are mixed.

**Comment by testn** [comment]
if you consider startup/shutdown scenario, `close()` method is not necessary called in the context.

**Comment by testn** [comment]
also if you call httpclient outside of `Context`, it will create a new `Context` every time.

**Comment by vietj** [comment]
the real problem comes from keep alive / pipelined connection, only in this case it would be effective. need to figure out the best that would work also in non context / verticle mode

**Comment by testn** [comment]
Even though you are running inside the verticle mode, you might have some library or code that use non-vert.x thread. If that code somehow has to call back to `HttpClient`, it might try to invoke that outside Vert.x event loop. In that case, it will keep create a new `Context` which can cause a deadlock. The only way to work around this is to pass `Context` around but it's quite difficult as well since `Context` is only created and accessible via Vert.x and it's created as needed so it is quite difficult to use it with IoC framework like Spring/Guice since you cannot really inject `Context` until you deployed it but you would want `Context` to inject into those objects so it becomes a chicken and egg problem.

**Comment by vietj** [comment]
I will have a look at the close.

**Comment by testn** [comment]
I think you agree that `close()` is much more likely to be called outside `Context` especially in the test code. So I think this has to be able to `close()` without causing a deadlock

**Comment by vietj** [comment]
I agree that this should be fixed.

**Comment by vietj** [comment]
I see more or less how it happens, however it is not really possible to come up with a reproducer. I will remove the synchronization in the client.close to remove the deadlock.

**Comment by testn** [comment]
@vietj With Vert.x 3.2.1, the deadlock still happens.

  java.lang.Thread.State: BLOCKED (on object monitor)
	at io.vertx.core.http.impl.ClientConnection.close(ClientConnection.java:371)
	- waiting to lock <0x00000000ece966f0> (a io.vertx.core.http.impl.ClientConnection)
	at io.vertx.core.http.impl.HttpClientImpl.close(HttpClientImpl.java:648)
	- locked <0x00000000ec4cc7c0> (a io.vertx.core.http.impl.HttpClientImpl)
.
.
.

"vert.x-eventloop-thread-2" #924 prio=5 os_prio=0 tid=0x00007f7884713000 nid=0x6e81 waiting for monitor entry [0x00007f7854d8a000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at io.vertx.core.http.impl.HttpClientImpl.checkClosed(HttpClientImpl.java:800)
	- waiting to lock <0x00000000ec4cc7c0> (a io.vertx.core.http.impl.HttpClientImpl)
	at io.vertx.core.http.impl.HttpClientImpl.doRequest(HttpClientImpl.java:791)
	at io.vertx.core.http.impl.HttpClientImpl.request(HttpClientImpl.java:338)
	at io.vertx.core.http.impl.HttpClientImpl.get(HttpClientImpl.java:348)
.
.
.

**Comment by vietj** [comment]
thanks, I'll look into it

**Comment by vietj** [comment]
can you open another issue for it ?

**Comment by kevlarC** [comment]
I think this is related to the deadlock report on https://github.com/eclipse/vert.x/issues/1355
