### ISSUE TITLE
HTTP/1.x server connection back-pressure management might reorder request body chunks

### ISSUE THREAD

**Issue by st-h** [eclipse/vert.x#2230]
As discussed [here](https://groups.google.com/forum/#!topic/vertx/7EPAUv73CtY) previously, starting with vert.x 3.5.0 I was noticing failing integration tests when uploading large (at least a few MB) files. The issue so far only appeared when running against mongo in a docker container or with travis ci. Downgrading to vert.x 3.4.0 seems to fix the issue. This issue does not appear on every build.
I once examined the differences between the uploaded and the persisted file and it showed that about the first 1054400 bytes were correctly persisted, but subsequent bytes were corrupt. I could not find any issues with file download. Just the upload seems to encouter this issue.

I have put a branch together which explicitly compares the md5 checksums of the uploaded file in addition to the actual bytes with vertx 3.5.1-SNAPSHOT [travis available here](https://travis-ci.org/st-h/vertx-mongo-streams/jobs/309572086) - [source](https://github.com/st-h/vertx-mongo-streams/tree/vertx-3.5.x)

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.github.sth.vertx.mongo.streams.GridFSInOutStreamIT
Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500} 
Opened connection [connectionId{localValue:1, serverValue:1}] to localhost:27017 
Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 4, 10]}, minWireVersion=0, maxWireVersion=5, maxDocumentSize=16777216, roundTripTimeNanos=4467832} 
Opened connection [connectionId{localValue:2, serverValue:2}] to localhost:27017 
uploaded file md5: e875acd2c89e7db444f04c54c5b01460
java.lang.AssertionError: uploaded file md5 does not match md5 calculated on server. Not equals : 31C48A5A246C9352E0EB846FEFD0A498 != E875ACD2C89E7DB444F04C54C5B01460 
Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500} 
Opened connection [connectionId{localValue:3, serverValue:3}] to localhost:27017 
Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 4, 10]}, minWireVersion=0, maxWireVersion=5, maxDocumentSize=16777216, roundTripTimeNanos=895998} 
Opened connection [connectionId{localValue:4, serverValue:4}] to localhost:27017 
Closed connection [connectionId{localValue:2, serverValue:2}] to localhost:27017 because the pool has been closed. 
Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500} 
Opened connection [connectionId{localValue:5, serverValue:5}] to localhost:27017 
Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 4, 10]}, minWireVersion=0, maxWireVersion=5, maxDocumentSize=16777216, roundTripTimeNanos=2004399} 
Opened connection [connectionId{localValue:6, serverValue:6}] to localhost:27017 
uploaded file md5: b563f831734cf630117017f006470f8a
Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500} 
No server chosen by WritableServerSelector from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, serverDescriptions=[ServerDescription{address=localhost:27017, type=UNKNOWN, state=CONNECTING}]}. Waiting for 30000 ms before timing out 
Closed connection [connectionId{localValue:6, serverValue:6}] to localhost:27017 because the pool has been closed. 
Opened connection [connectionId{localValue:7, serverValue:7}] to localhost:27017 
Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 4, 10]}, minWireVersion=0, maxWireVersion=5, maxDocumentSize=16777216, roundTripTimeNanos=651115} 
Opened connection [connectionId{localValue:8, serverValue:8}] to localhost:27017 
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.561 sec <<< FAILURE! - in com.github.sth.vertx.mongo.streams.GridFSInOutStreamIT
testUploadAndDownloadLarge(com.github.sth.vertx.mongo.streams.GridFSInOutStreamIT)  Time elapsed: 4.324 sec  <<< FAILURE!
java.lang.AssertionError: uploaded file md5 does not match md5 calculated on server. Not equals : 31C48A5A246C9352E0EB846FEFD0A498 != E875ACD2C89E7DB444F04C54C5B01460
```

[this](https://travis-ci.org/st-h/vertx-mongo-streams/builds/308699557) is a build using vertx 3.4.0 which never failed so far

**Comment by vietj** [comment]
can you make a simple reproducer with vertx core ?

**Comment by st-h** [comment]
well, I will try to find time to do so. But the issue currently is, I don't have any idea what the actual cause might be. Could be a vertx dependency. Could be the http implementation. Could be something stream related like a pump or so, or something entirely different. Considering that this only shows up under certain (load) conditions, this might be very difficult to replicate just using vertx core. Even how mongo is run seems to make a difference. I did a quick check yesterday if a plain upload works fine and it seemed to do so. Considering the circumstances this issue is showing up, this however does not mean anything substantial. Currently there is a chance that under certain conditions someone using vertx >= 3.5.0 or the mentioned library will be left with corrupt data. I don't really know how to figure out for sure if it is the one or the other that is the case. The only thing that I can say with certainty is that I have never seen this issue with vertx versions below 3.5.0 - but even that does not mean that is for sure that it hasn't existed previously but never showed up.

**Comment by vietj** [comment]
I will give it a try, it sounds fairly easy to run locally

**Comment by vietj** [comment]
with this test it is complicated to determine wether the issue is between the test and the IntegrationTestVerticle or the IntegrationTestVerticle and Mongo. I've tried to reproduce it using Mongo on my machine but after many runs (300) it never happens.

Can you try with this branch https://github.com/vietj/vert.x/tree/http-improvements-more ? it fixes the race issue that is observed when using `HttpClient` outside of the event loop (like in your test).

**Comment by st-h** [comment]
Thank you for checking. I know this is madness with that many things involved...
I replaced vertx-core with the one build from the mentioned branch and I wasn't able replicate the issue so far. Usually it takes me about a max of 5 builds and I get a failing one. When will this be released? I would like to make sure this works with travis ci as well. But so far this is good news!
btw... did you run against a local mongo or mongo running in a docker container?

**Comment by vietj** [comment]
@st-h I'm glad it fixes it, I'm suspecting this issue https://github.com/eclipse/vert.x/issues/2218 .

I've merged it in master, can you have a check with vertx 3.5.1-SNAPSHOT ?

we aim to release 3.5.1 early 2017.

**Comment by vietj** [comment]
I will close this issue for now.

**Comment by st-h** [comment]
Unfortunately this still fails with vertx 3.5.1-SNAPSHOT as seen [here](https://travis-ci.org/st-h/vertx-mongo-streams/branches). The 1.3.0 branch uses vert.x `3.4.0` whereas the vertx-3.5.x branch currently loads `3.5.1-SNAPSHOT`. vertx `3.4.0` constantly works fine, while  `3.5.x` easily leads to failed tests when run against a docker container. Easy fix for us would be to just stay with vertx 3.4.0 for our library, as this is just the version used for tests. However this still leaves the risk that something is broken either with vert.x 3.5.0 or our library in combination with current vertx version. I will try to find time to dig around some more, but I can only urge to reopen this issue.

**Comment by vietj** [comment]
@st-h right, I reopen the issue, it would be awesome if you can find what is going on.

my advice also is that your current tests, tests 2 things: JUnit -> Verticle -> Mongo

we need to consider two cases here:

- JUnit -> Verticle  (uses Vert.x client and server)
- Verticle -> Mongo (uses Vert.x client only)

to isolate if the issue comes from `HttpClient` or `HttpServer`

can you take care of this in your test first ?

**Comment by st-h** [comment]
@vietj thank you and I got some more information:

- First I refactored all tests to java to make sure this is not related to any changes made in vert.x 3.4.0 or 3.5 to the groovy implementations (not sure what has been done exactly when behind the scenes, but that was when the migration notes appeared). However, this did not make any difference at all.
- Then I modified the WriteStream implementation of the library to copy all bytes provided in `public WriteStream<Buffer> write(Buffer inputBuffer)` to a dedicated array to see if the error lies within the data provided by vertx ([see code](https://github.com/st-h/vertx-mongo-streams/blob/8c00c281a5d2539f143deccd59536d8de8e7dc8a/src/main/java/com/github/sth/vertx/mongo/streams/GridFSInputStreamImpl.java#L94)). These are the md5s I am calculating at various stages:
```
client: md5 from bytes to be uploaded:             3A572E13FD2279C96636C6E61D6AD1A8
server: bytes provided by WriteStream:            AA1C4C8441EC8463DF670F9CD87F55A4
server: upload md5 from persisted gridFS file: AA1C4C8441EC8463DF670F9CD87F55A4
```
So the issue seems to be that the data I am uploading is not the same as I am receiving within the WriteStream implementation.
Given that the actual implementation of the verticle merely consists of a Pump which provides data to the WriteStream implementation which I use to calculate mentioned md5 and the fact that the implementation works for smaller files and everything worked flawlessly prior to vertx 3.5.0, I highly suspect that this is a regression within vertx.

**Comment by st-h** [comment]
I made a journey through history today. Within the limit ways of testing this issue currently leaves I found that the first commit where I was able to reproduce the error is `162e5cf0511ca69a9c168b251f6ce537e7a10173` `Try to simplify the queuing check with a cache of the queuing condition` . I was not able to reproduce the issue with the three commits made earlier like `b484db818d3aa6eeaa8c3ca7053d5c10f0295823`. I am gonna leaves this to you guys for now as I am totally unaware of what was trying to be accomplished by this commit nor what is correct behaviour and what not. Please let me know if there is anything I should test or check etc...

**Comment by st-h** [comment]
Oh btw, I found that if using a more performant machine when running the test it helps to increase the size of the uploaded file in the integration test to more often expose the issue like so:
```
    @Test
    public void testUploadAndDownloadLarge(TestContext context) {
        byte[] bytes = ByteUtil.randomBytes(1024 * 1024 * 170)
        uploadDownload(context, bytes)
    }
```

**Comment by vietj** [comment]
so the issue is due to data sent by the client to an Vertx Http Server ?

**Comment by st-h** [comment]
@vietj not sure if I understand your question correctly, but all I can say for sure is the following: There seems to be evidence that the mentioned commit introduced some sort of race condition or edge case, where vertx provides incorrect data to a WriteStream implementation when a file is uploaded by the vertx client, which seems to show up only under certain (load) conditions. So, yes the issue only shows up if there is a client which sends data to the vertx http server. Secondly it seems that the size of the data seems to be of importance as well. Theoretically from what I tested, there is a chance that vertx http client is causing the issue as well as I haven't tried to reproduce the issue using different clients.

**Comment by vietj** [comment]
my point is that the reproducer uses different portion of vertx : HttpClient and HttpServer , I'm trying to nail down to which part it belongs to. So it would be good to have a minimal reproducer so it's easier to nail it down.

**Comment by vietj** [comment]
The commit "Try to simplify the queuing check with a cache of the queuing condition" affects the vertx HttpServer HTTP/1 message processing that's why I'm saying it seems that the issue is when the http server process a body entity and that's where research should focus.

**Comment by st-h** [comment]
> it seems that the issue is when the http server process a body entity and that's where research should focus.

Yeah, that is what my gut is telling me as well. I know these kind of bugs are a pain to deal with and I wish I would be able to provide a simpler reproducer. But so far I am glad that I have even been able to reproduce the issue locally at all and figure out which commit seemed to introduce the bug, which has been quite a pain itself 🤕 . I wrote a [test](https://github.com/st-h/vertx-mongo-streams/blob/master/src/test/groovy/com/github/sth/groovy/vertx/mongo/streams/GridFSInputStreamConcurrencyTest.groovy) that just launches two threads that run the concurrent procedures against each other to spot any race conditions within the vertx-mongo-streams library as a good looking PR had introduced a similar issue a while back. Maybe there is a possibility to do something similar regarding the mentioned commit. Or maybe we could rollback that change and see if things are good again - but it looks like things have been moved around quite a bit since then, which makes it difficult to judge for me if this might be an option.

**Comment by vietj** [comment]
@st-h the first priority is to exhibit the simplest reproducer we can have in Vert.x test suite and then we can discuss the the options of the fix

**Comment by vietj** [comment]
@st-h I'm actually planning to rewrite the back-pressure handling of `Http1xServerConnection` also that's why I think the most valuable thing is the reproducer to avoid regressions

**Comment by vietj** [comment]
btw is the client pipelined in your tests ?

**Comment by st-h** [comment]
> the first priority is to exhibit the simplest reproducer we can have in Vert.x test suite and then we can discuss the the options of the fix

If you know any way to reproduce this simpler, for any means please do so. I unfortunately don't so far. But leaving it like everything is, might be causing huge issues in production. It probably just is a matter of time, people will run into this with 3.5.0. To me it seems much more important to get rid of the regression and get a fix out asap before this is causing any real damage.

> btw is the client pipelined in your tests ?

I don't think it is pipelined, at least it is not explicitly enabled and should be disabled by default. But even though, the test consists of a single file upload (which already shows the regression) and a corresponding download (which verifies the regression), so I don't think this should be related. Test is here btw: https://github.com/st-h/vertx-mongo-streams/blob/master/src/test/groovy/com/github/sth/groovy/vertx/mongo/streams/GridFSInOutStreamIT.groovy

**Comment by vietj** [comment]
I will try to make a reproducer based on the context you provide

**Comment by vietj** [comment]
@st-h you said:

"Within the limited ways of testing this issue currently leaves I found that the first commit where I was able to reproduce the error is 162e5cf0511ca69a9c168b251f6ce537e7a10173 Try to simplify the queuing check with a cache of the queuing condition . I was not able to reproduce the issue with the three commits made earlier like b484db818d3aa6eeaa8c3ca7053d5c10f0295823. "

it's unclear what means the "three commits" earlier, can you elaborate ?

**Comment by st-h** [comment]
sure. I was going back in time from now and the first commit that showed the issue was `162e5cf0511ca69a9c168b251f6ce537e7a10173`. Then I tested the three commits that were made earlier (are older) and none of these builds would show the regression. However, every build that was after `162e5cf0511ca69a9c168b251f6ce537e7a10173` (commits that are younger) showed the issue. Therefore I came to the conclusion that the issue must have been introduced in `162e5cf0511ca69a9c168b251f6ce537e7a10173`

**Comment by vietj** [comment]
are you able to make this fail on your desktop ? I've cloned your repo and when I run the IT tests with a Docker image, I'm not able to get the failure

**Comment by vietj** [comment]
@st-h I still don't get the three commits : where does this magic number comes from ?

**Comment by st-h** [comment]
I have been able to make this fail on a macbook and a macbook pro. The pro however needs much bigger files to show the issue. Are you running `mvn verify`?

three commits ain't no magic number. I just stopped going back in time after I wasn't able to reproduce the issue any more trying three subsequent commits. It could have been 5 or 20. I just figured it would be enough to check three different builds from subsequent commits that work fine to ensure that the issue hasn't been introduced earlier.

**Comment by vietj** [comment]
I'm on a MBP, I'm trying indeed verify.

Can you make a branch in your repo that reproduces on MBP with instructions how to run it including docker ?

**Comment by st-h** [comment]
and possibly another clue. When the test fails, I can observe the following call structure:
```
handleMessage
processMessage
pause
handleMessage
enqueue             // 1 message enqueued
resume
handleMessage      // after resume the message does not get processed before the next is handled
processMessage
```
What I noticed is that when the upload fails:
- an enqueue happens
- after resume no processMessage is called

If the upload does not fail, after an enqueue there always seems to be the right number of calls to processMessage to handle all enqueue messages.

Just digging around, so this might be related - or maybe not.


> Can you make a branch in your repo that reproduces on MBP with instructions how to run it including docker ?

The [java-test](https://github.com/st-h/vertx-mongo-streams/tree/java-tests) branch should fail on a MBP. I am just running `mvn verify`. This is the docker command `docker run -d -p 127.0.0.1:27017:27017 mongo` I am using. But you can always increase the file size as mentioned above within the `testUploadAndDownloadLarge` test.

**Comment by vietj** [comment]
@st-h that's the impression I had too when looking at the commit, I will try the reproducer (again) asap.

**Comment by vietj** [comment]
@st-h how many times do you need to run it to get the failure ?

**Comment by vietj** [comment]
ah it seems to happen but the test does not fail per se

**Comment by vietj** [comment]
it just prints the different hashes

**Comment by vietj** [comment]
well i could observe it once and has to icnrease the size to 170 instead of 17

**Comment by st-h** [comment]
yeah, it does not necessarily fail every time. That's why it's so difficult to reproduce. You need to create a situation where methods are called in parallel at the right timing. And that also is why it is so difficult to write meaningful tests that would catch those things. Do you need further help with this? I think it would be best to rewrite the queue and the flags. But as you already had some refactorings planned maybe that does not make too much sense. Let me know how you would like to progress.

**Comment by vietj** [comment]
actually I'm not able to reproduce it at all so far

**Comment by vietj** [comment]
what do you mean by parallel ?

**Comment by vietj** [comment]
_ If now handleMessage() gets called between setting queueing and calling checkNextTick()_ that should not be possible as it's the same thread (event loop), specifically in your case it's an http server verticle and there is no other thread involved as far as I can see

**Comment by vietj** [comment]
ah perhaps you mean that gridFSBucket.uploadFromStream callback is performed from another thread managed by Mongo ?

**Comment by vietj** [comment]
I see now where the other thread is coming from : (that does not excuse the potential race in Vert.x). 

I think your `GridFSInputStream` should capture the Vert.x context when you create it and drain handler callbacks should be done on that Context to use the same EL thread.

**Comment by st-h** [comment]
> actually I'm not able to reproduce it at all so far

Oh, sorry. I was under the impression that you meant that you were able to observe the issue once with that message
> well i could observe it once and has to icnrease the size to 170 instead of 17

> what do you mean by parallel ?

From what I observed, the `handleMessage` method seems to be called before the `resume`  method is finished. Which would also explain the race condition that the travis test seems to show. The code as it currently is would at least not be safe to be used in that way, as the flags that describe the queue and the actual queue could diverge and be in a different state. If it is ensured by the caller that the class is never ever used in such a way, that however should be ok.

**Comment by st-h** [comment]
> I think your GridFSInputStream should capture the Vert.x context when you create it and drain handler callbacks should be done on that Context to use the same EL thread.

do you mean by making use of `vertx.runOnContext()`? I'll be very happy if we can improve the library...

**Comment by vietj** [comment]
@st-h yes I meant that

**Comment by vietj** [comment]
_Oh, sorry. I was under the impression that you meant that you were able to observe the issue once with that message_ : the difference case when printed got me wrong.

I'm still trying to reproduce it though.

What is your reproduction rate on your laptop ?

**Comment by vietj** [comment]
got a failure!

```
  GridFSInOutStreamIT.lambda$5:129 uploaded file md5 does not match md5 calculated on server. Not equals : 93C45ED9DCE6D1F2A41EE9605D87D925 != EDB2C8AFE2C5B38EC554B7E5B97CA729
```

**Comment by st-h** [comment]
> What is your reproduction rate on your laptop ?

I get a failure on almost every build currently using `ByteUtil.randomBytes(1024 * 1024 * 4)` as payload on the MacBook. But I guess it depends on how may other things are hogging resources. Maybe that's why it easily show up on travis because they might be using very small VMs. Less available resources seems to make it more easy to reproduce.

**Comment by vietj** [comment]
what's your laptop config ?

**Comment by vietj** [comment]
can you try try: in `checkNextTick()` wrap the `runOnContext` in a synchronised block:

```
        // Should be synchronized ...
        synchronized (Http1xServerConnection.this) {
          sentCheck = false;
          if (!queueing) {
            Object msg = pending.poll();
            if (msg != null) {
              if (msg instanceof HttpRequest && pendingResponse != null) {
                pending.addFirst(msg);
                queueing = true;
                return;
              }
              processMessage(msg);
            }
            if (channelPaused && pending.isEmpty()) {
              //Resume the actual channel
              Http1xServerConnection.super.doResume();
              channelPaused = false;
            }
          }
        }
```

**Comment by vietj** [comment]
I've been able to reproducer it in this CI (slow) : https://vietj.ci.cloudbees.com/job/vertx-mongo-streams/10/console but it does not fail often

**Comment by vietj** [comment]
@st-h can you give a try with using vertx-core (only core) version 3.5.0-fix-SNAPSHOT ? it's a SNAPSHOT I've  deployed that wraps synchronises the callback block

**Comment by st-h** [comment]
> I think your GridFSInputStream should capture the Vert.x context when you create it and drain handler callbacks should be done on that Context to use the same EL thread.

First off, I tried to make use of runOnContext when calling the drain handler like below. This does not seem to improve the problem in any way. Is that what you meant? I also tried to wrap the whole content of this method, but the results were the same

```
    private void doCallback(final ByteBuffer b, final SingleResultCallback<Integer> c) {
        pendingCallback = null;
        outputBuffer = null;
        final int bytesWritten = buffer.drainInto(b);
        c.onResult(bytesWritten, null);
        // if there is a drain handler and the buffer is less than half full, call the drain handler
        if (drainHandler != null && buffer.remaining() < writeQueueMaxSize / 2) {
            final Handler<Void> d = drainHandler;
            vertx.runOnContext(v -> d.handle(null));
            drainHandler = null;
        }
    }
```

> can you give a try with using vertx-core (only core) version 3.5.0-fix-SNAPSHOT ?

I tried, but that build fails as well :( here is the dependency tree
```

[INFO] com.github.st-h:vertx-mongo-streams:jar:1.3.1-SNAPSHOT
[INFO] +- io.vertx:vertx-unit:jar:3.5.0-SNAPSHOT:test
[INFO] +- io.vertx:vertx-core:jar:3.5.0-fix-SNAPSHOT:provided
[INFO] |  +- io.netty:netty-common:jar:4.1.15.Final:provided
[INFO] |  +- io.netty:netty-buffer:jar:4.1.15.Final:provided
[INFO] |  +- io.netty:netty-transport:jar:4.1.15.Final:provided
[INFO] |  +- io.netty:netty-handler:jar:4.1.15.Final:provided
[INFO] |  |  \- io.netty:netty-codec:jar:4.1.15.Final:provided
[INFO] |  +- io.netty:netty-handler-proxy:jar:4.1.15.Final:provided
[INFO] |  |  \- io.netty:netty-codec-socks:jar:4.1.15.Final:provided
[INFO] |  +- io.netty:netty-codec-http:jar:4.1.15.Final:provided
[INFO] |  +- io.netty:netty-codec-http2:jar:4.1.15.Final:provided
[INFO] |  +- io.netty:netty-resolver:jar:4.1.15.Final:provided
[INFO] |  +- io.netty:netty-resolver-dns:jar:4.1.15.Final:provided
[INFO] |  |  \- io.netty:netty-codec-dns:jar:4.1.15.Final:provided
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.9.0:provided
[INFO] |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.9.0:provided
[INFO] |     \- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:provided
[INFO] +- io.vertx:vertx-lang-groovy:jar:3.5.0-SNAPSHOT:provided
[INFO] |  \- org.codehaus.groovy:groovy-all:jar:2.4.7:provided
[INFO] +- org.mongodb:mongodb-driver-async:jar:3.3.0:provided
[INFO] |  +- org.mongodb:bson:jar:3.3.0:provided
[INFO] |  \- org.mongodb:mongodb-driver-core:jar:3.3.0:provided
[INFO] +- io.vertx:vertx-core:test-jar:tests:3.5.0-SNAPSHOT:test
[INFO] \- junit:junit:jar:4.12:test
[INFO]    \- org.hamcrest:hamcrest-core:jar:1.3:test

```
>  it's a SNAPSHOT I've deployed that wraps synchronises the callback block

Don't know how that code looks like now, but just synchronising will not be enough as long as there are flags modified outside of the synchronized block, which the synchronized block relies on.  I can put together a PR, but as said that does not make much sense if you want to refactor anyway, as that most likely will not be an easy fix.

> I've been able to reproduce it in this CI (slow) : https://vietj.ci.cloudbees.com/job/vertx-mongo-streams/10/console but it does not fail often

yes and we should all be happy about that. Considering that some people might already have deployed 3.5.0 to production. That would be a load of fun if that race condition would show up more easily.

**Comment by vietj** [comment]
can you put the PR ? I'm not sure I want to refactor that in the timeframe of 3.5.1 actually

**Comment by st-h** [comment]
I’ll see what I can do. Can you tell me more details about what you had in mind regarding the refactoring? As I’ll probably be rewriting some things I maybe can already implement some of those things you have in mind.

**Comment by vietj** [comment]
@st-h currently the `pending` queue holds the pending HTTP messages which are most of the time `HttpContent` but also `HttpRequest` when the client pipelines (and which makes the code very complicated). I would like to split and replace the pending queue by two queues:

- the pending `HttpContent` of the current request to be held in a `Deque<HttpContent>` in `HttpServerRequestImpl`
- the pending `HttpServerRequestImpl` in a queue `Deque<HttpServerRequestImpl>`

So the `Deque< HttpServerRequestImpl >` is only manipulated by request ending / response ending and the `HttpServerRequestImpl` resume/pause back-pressure is managed in the request and not in the connection (but it can pause reading from the network like it is today).

**Comment by vietj** [comment]
@st-h can you tell me how to run it in Travis CI from my own project fork ?

**Comment by st-h** [comment]
ok, thanks. I'll see what I can do. Not totally sure right now if there will be any implications by having two queues and the priority they should be consumed at, but that might clear up by its self when I get a clear picture of the code.

> can you tell me how to run it in Travis CI from my own project fork ?

Once you log into travis, you should be able to just enable your repository from there. That should be everything you need to do, as the config file already is present in the repo

**Comment by vietj** [comment]
@st-h the two queues shall be actually simpler because they are not used with the same objects and don't react on the same event. The request queue reacts on HttpRequest/LastHttpContent and the content per request queue only cares about buffers.

**Comment by vietj** [comment]
@st-h can you try this artifact : https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-core/3.5.0-fix-SNAPSHOT/ based on this branch https://github.com/vietj/vert.x/tree/server-bp-fix that is an attempt to fix the issue (that I identified)

**Comment by st-h** [comment]
Yes, this seems to look good to me. Both from the changes to the code as well as from [travis](https://travis-ci.org/st-h/vertx-mongo-streams/builds/326906950).

But yet again. How to go on? Shall we rewrite some of that stuff, or leave it for now?

**Comment by vietj** [comment]
awesome.

I believe the fix is good, however I still see some potential bugs with pipelining, so I will add more tests and more fixes in this branch and we will rerun your tests to ensure everything is fine. Once it is achieved, I'll clean up the branch (remove the debugging code) and make a PR for 3.5.1.

**Comment by st-h** [comment]
Alright, I won't be working on a PR then. I believe we could improve some of how the code is structured to avoid bugs, but I don't yet fully understand everything what is going on, so I don't want to be too quick on this. But it would most likely be quite a rewrite anyhow.

**Comment by st-h** [comment]
However, one last question about the vertx-mongo-streams library. All making use of runOnContext currently seems to do is break some unit tests. Does that make sense in the way I posted above?

**Comment by vietj** [comment]
@st-h can you make a PR on your own project and then I can review the diff and comment ?

**Comment by st-h** [comment]
@vietj one question regarding pipelining: If a new HttpRequest is received within processMessage, but there also is a current request being processed, the new request is queued. 
```
  private void processMessage(Object msg) {
    if (msg instanceof HttpRequest) {
      if (pendingResponse != null) {
        enqueue(msg);
        return;
      }
```
Is it ensured from "outside" that there will be no content received on the connection for the queued request until the handler of the requestHandler is called with that request?
```
requestHandler.handle(req);
```

I am asking because I am wondering if we actually need to support multiple requests per connection, or if any further requests just will be queued and no content will be transmitted and it is sufficient if we just manage one request per connection. So to speak: If there is a current request, we queue the new one. If the current one is finished, all received content is meant to be consumed by the previously queued request?

**Comment by vietj** [comment]
@st-h if a pipelined request arrives while the current request is not yet finished then it is enqueued, the `queuing` flag is set to `true` and all further messages are added to the `pending` queue. When the current request ends, the `responseComplete()` method set the `queueing` flag to `false` (actually to `paused` but in general case `paused` == `true`) and the call to `checkNextTick()` will poll the next message that is the `HttpRequest` message and it will be processed with the content messages.

**Comment by st-h** [comment]
@vietj the thing I am missing in my head is that if all message are added to the pending queue after the second request arrives while the first one is still in progress, aren't we putting both message (from 1st and 2nd request) on the queue? If we later consume that again, were is the reference which message belongs to which request? How do we find out which HttpContent belongs to which HttpServerRequest?

**Comment by vietj** [comment]
when the second requests arrives, all the messages from the first requests are already in the queue in the right order, so we have likely in the queue : `HttpContent[1], HttpContent[1],LastHttpContent[1],HttpRequest[2],HttpContent[2],...`

**Comment by st-h** [comment]
@vietj ah perfect. thank you.

**Comment by vietj** [comment]
@st-h do you mind to test and validate this final branch https://github.com/eclipse/vert.x/tree/http1-server-conn-backpressure-improvements ?

**Comment by st-h** [comment]
@vietj will do.
From looking at the tests, I assume we cannot process pipelined requests in parallel? Or to put it another way: We need to wait in the ServerConnection for req1 to be done (responseComplete?) before we can start processing req2?

**Comment by vietj** [comment]
@st-h indeed it's not possible and not a good idea, because it adds more complexity (so potential bugs) and force to buffer responses. If you need more concurrency and you control the protocol, use HTTP/2 instead.

**Comment by st-h** [comment]
> @st-h do you mind to test and validate this final branch https://github.com/eclipse/vert.x/tree/http1-server-conn-backpressure-improvements ?

@vietj seems to work on my machine™

**Comment by vietj** [comment]
before making a PR, i'll try to make a reproducer for master as safe-guard

**Comment by vietj** [comment]
I've added a reproducer for the issue - it fails for master and works with this fix - it reproduce a similar pause/resume mechanism that is done in your test, where the resume happens to be done by a non vertx thread (in your case the mongo client thread) and can lead to the reordering of http content chunks
